version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node_api:
    build:
      context: ./sakura-api
    container_name: sakura-api-container
    environment:
      - PORT=7000
      - MONGO_DATABASE_HOST=mongodb://mongodb:27017 # Full MongoDB connection URI
    depends_on:
      - mongodb
    volumes:
      - ./sakura-api:/app # Mount local Node.js code
    command: npx nodemon dist/index.js # Use nodemon for live reload
    ports:
      - "7000:7000" # Example port for signal server

  signal_server:
    build:
      context: ./sakura-signal
    container_name: sakura-signal-container
    environment:
      - REDIS_HOST=redis
      - MEDIA_SERVER_HOST=go_service # Hostname for Go Service
    depends_on:
      - redis
      - go_service
    volumes:
      - ./sakura-signal:/app # Mount local Node.js code
    command: npx nodemon index.js # Use nodemon for live reload
    ports:
      - "5000:5000" # Example port for signal server

  # react_app:
  #   build:
  #     context: ./sakura-app
  #   container_name: sakura-app-container
  #   stdin_open: true
  #   volumes:
  #     - ./sakura-app:/app # Mount local React code
  #   command: npm start # Use React's development server
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_SOCKET_SERVER_HOST=localhost
  #   ports:
  #     - "3000:3000" # React app exposed on 3000

  go_service:
    build:
      context: ./sakura-media-server
    container_name: sakura-go-media-server-container
    environment:
      - SIGNAL_SERVER_HOST=signal_server # Hostname for Signal Server
      - SIGNAL_SERVER_PORT=5000
      - NODE_API_HOST=node_api
      - NODE_API_PORT=7000
    depends_on:
      - node_api
    ports:
      - "4000:4000"

volumes:
  mongo-data: