package sfu

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/joho/godotenv"
	"github.com/pion/interceptor"
	"github.com/pion/interceptor/pkg/intervalpli"
	"github.com/pion/webrtc/v4"

	"github.com/pion/webrtc/v4/pkg/media"
	"github.com/pion/webrtc/v4/pkg/media/oggreader"

	"sakura/models"
	"sakura/roommanager"
	"sakura/utils"
)

func getServerURL(prefix string) string {
	// Load environment variables from .env file
	err := godotenv.Load()
	if err != nil {
		log.Fatalf("Error loading .env file: %v", err)
	}

	signalHost := os.Getenv("SIGNAL_SERVER_HOST")
	signalPort := os.Getenv("SIGNAL_SERVER_PORT")

	if signalHost == "" && signalPort == "" {
		log.Fatalf("Environment variables are not set")
	}

	// Construct the URL using the environment variables
	return fmt.Sprintf("http://%s:%s/media-server/%s", signalHost, signalPort, prefix)
}

func getMediaManagerURL() string {
	// Load environment variables from .env file
	err := godotenv.Load()
	if err != nil {
		log.Fatalf("Error loading .env file: %v", err)
	}

	signalHost := os.Getenv("MEDIA_MANAGER_HOST")
	signalPort := os.Getenv("MEDIA_MANAGER_PORT")

	if signalHost == "" && signalPort == "" {
		log.Fatalf("Environment variables are not set")
	}

	fmt.Printf("Media manager server %s\n", fmt.Sprintf("http://%s:%s/", signalHost, signalPort))

	// Construct the URL using the environment variables
	return fmt.Sprintf("http://%s:%s/", signalHost, signalPort)
}

func GetMediaManagerURL() string {
	return getMediaManagerURL()
}

// Define the URL as a constant
var serverURL string = getServerURL("answer")
var serverURLrenegot string = getServerURL("renegot")

func RunReflectServer(sdpRequest models.SDPRequest, room *models.Room, participant *models.Participant) {
	// Everything below is the Pion WebRTC API! Thanks for using it ❤️.

	// Create a MediaEngine object to configure the supported codec
	m := &webrtc.MediaEngine{}

	// Setup the codecs you want to use (Opus for audio)
	if err := m.RegisterCodec(webrtc.RTPCodecParameters{
		RTPCodecCapability: webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus, ClockRate: 48000, Channels: 2, SDPFmtpLine: "", RTCPFeedback: nil},
		PayloadType:        111,
	}, webrtc.RTPCodecTypeAudio); err != nil {
		panic(err)
	}

	// Create a InterceptorRegistry. This is the user configurable RTP/RTCP Pipeline.
	// This provides NACKs, RTCP Reports and other features. If you use `webrtc.NewPeerConnection`
	// this is enabled by default. If you are manually managing You MUST create a InterceptorRegistry
	// for each PeerConnection.
	i := &interceptor.Registry{}

	// Use the default set of Interceptors
	if err := webrtc.RegisterDefaultInterceptors(m, i); err != nil {
		panic(err)
	}

	// Register a intervalpli factory
	// This interceptor sends a PLI every 3 seconds. A PLI causes a video keyframe to be generated by the sender.
	// This makes our video seekable and more error resilent, but at a cost of lower picture quality and higher bitrates
	// A real world application should process incoming RTCP packets from viewers and forward them to senders
	intervalPliFactory, err := intervalpli.NewReceiverInterceptor()
	if err != nil {
		panic(err)
	}
	i.Add(intervalPliFactory)

	// Create the API object with the MediaEngine
	api := webrtc.NewAPI(webrtc.WithMediaEngine(m), webrtc.WithInterceptorRegistry(i))

	// Prepare the configuration
	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}
	// Create a new RTCPeerConnection
	peerConnection, err := api.NewPeerConnection(config)
	if err != nil {
		panic(err)
	}
	defer func() {
		if cErr := peerConnection.Close(); cErr != nil {
			fmt.Printf("cannot close peerConnection: %v\n", cErr)
		}
	}()

	// Create Track that we send video back to browser on
	outputTrack, err := webrtc.NewTrackLocalStaticRTP(webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus}, "audio", "pion")
	if err != nil {
		panic(err)
	}

	// Add this newly created track to the PeerConnection
	rtpSender, err := peerConnection.AddTrack(outputTrack)
	if err != nil {
		panic(err)
	}

	// Store the track in the participant's Tracks map
	participant.Tracks[outputTrack.ID()] = outputTrack

	// Read incoming RTCP packets
	// Before these packets are returned they are processed by interceptors. For things
	// like NACK this needs to be called.
	go func() {
		rtcpBuf := make([]byte, 1500)
		for {
			if _, _, rtcpErr := rtpSender.Read(rtcpBuf); rtcpErr != nil {
				return
			}
		}
	}()

	// Wait for the offer to be pasted
	offer := webrtc.SessionDescription{}
	utils.Decode(sdpRequest.SDP, &offer)

	// Set the remote SessionDescription
	err = peerConnection.SetRemoteDescription(offer)
	if err != nil {
		panic(err)
	}

	// Update participant's PeerConnection
	participant.Mutex.Lock() // Locking to avoid race condition
	participant.PeerConnection = peerConnection
	participant.Mutex.Unlock()

	roommanager.PrintRooms()

	// Set a handler for when a new remote track starts, this handler copies inbound RTP packets,
	// replaces the SSRC and sends them back
	peerConnection.OnTrack(func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) { //nolint: revive
		fmt.Printf("Track has started, of type %d: %s \n", track.PayloadType(), track.Codec().MimeType)
		for {
			// Read RTP packets being sent to Pion
			rtp, _, readErr := track.ReadRTP()
			if readErr != nil {
				panic(readErr)
			}

			// if writeErr := outputTrack.WriteRTP(rtp); writeErr != nil {
			// 	panic(writeErr)
			// }

			roommanager.Wrtp(rtp)
		}
	})

	// Set the handler for Peer connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnConnectionStateChange(func(s webrtc.PeerConnectionState) {
		fmt.Printf("Peer Connection State has changed: %s\n", s.String())

		if s == webrtc.PeerConnectionStateClosed || s == webrtc.PeerConnectionStateFailed {
			// Remove participant from the room
			roommanager.RemoveParticipantFromRoom(sdpRequest.RoomID, participant.ClientID)
		}
	})

	// Create an answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	// Create channel that is blocked until ICE Gathering is complete
	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)

	// Sets the LocalDescription, and starts our UDP listeners
	if err = peerConnection.SetLocalDescription(answer); err != nil {
		panic(err)
	}

	// Block until ICE Gathering is complete, disabling trickle ICE
	// we do this because we only can exchange one signaling message
	// in a production application you should exchange ICE Candidates via OnICECandidate
	<-gatherComplete

	// Output the answer in base64 so we can paste it in browser
	encodedAnswer := utils.Encode(peerConnection.LocalDescription())

	// Send remote SDP data to signalling server
	// Create JSON payload to send to localhost:4000
	payload := map[string]string{
		"clientId":  sdpRequest.ClientID,
		"sdpAnswer": encodedAnswer,
	}

	// Convert payload to JSON format
	jsonData, err := json.Marshal(payload)
	if err != nil {
		panic(err)
	}

	// Create a new HTTP POST request
	req, err := http.NewRequest("POST", serverURL, bytes.NewBuffer(jsonData))
	if err != nil {
		fmt.Printf("Failed to create POST request: %v\n", err)
		return
	}

	// Set the Content-Type and x-api-key headers
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", "your-secret-key")

	// Send the request
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Printf("Failed to send POST request: %v\n", err)
		return
	}
	defer resp.Body.Close()

	// Check response status
	if resp.StatusCode == http.StatusOK {
		fmt.Println("Successfully sent answer to server")
	} else {
		fmt.Printf("Failed to send answer with status code: %d\n", resp.StatusCode)
	}

	// Block forever
	select {}
}

var mediaManagerURL string = getMediaManagerURL()
var audioURL = mediaManagerURL + "media/_Fo6n3nl_Sk"

const (
	oggPageDuration = time.Millisecond * 20
)

func BotStart() *webrtc.TrackLocalStaticSample {
	// Fetch the audio file from HTTP API
	resp, err := http.Get(audioURL)
	if err != nil {
		fmt.Println("Failed to fetch audio file.")
		return nil
	}

	// Create an audio track for music
	musicTrack, err := webrtc.NewTrackLocalStaticSample(webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus}, "audio-music", "pion-music")
	if err != nil {
		panic(err)
	}

	go func() {
		ogg, _, err := oggreader.NewWith(resp.Body)
		if err != nil {
			panic(err)
		}

		ticker := time.NewTicker(oggPageDuration)
		defer ticker.Stop()

		var lastGranule uint64
		for range ticker.C {
			pageData, pageHeader, err := ogg.ParseNextPage()
			if errors.Is(err, io.EOF) {
				fmt.Println("All audio pages parsed.")
				break
			}
			if err != nil {
				panic(err)
			}

			sampleCount := float64(pageHeader.GranulePosition - lastGranule)
			lastGranule = pageHeader.GranulePosition
			sampleDuration := time.Duration((sampleCount/48000)*1000) * time.Millisecond

			if writeErr := musicTrack.WriteSample(media.Sample{Data: pageData, Duration: sampleDuration}); writeErr != nil {
				panic(writeErr)
			}
		}

		// Close the response body once the audio processing is done
		if resp.Body != nil {
			resp.Body.Close()
		}
	}()

	return musicTrack
}

func DoRenegotiationAll() {
	roommanager.RenegotAll(serverURLrenegot)
}

// Start the Bot to add music track
func StartMusicEverywhere() {
	DoRenegotiationAll()
}

func CreateAudioTrack() *webrtc.TrackLocalStaticSample {
	// Create an audio track for music
	musicTrack, err := webrtc.NewTrackLocalStaticSample(webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus}, "audio-music", "pion-music")
	if err != nil {
		panic(err)
	}
	return musicTrack
}

func WriteAudioToTrack(audioURL string, musicTrack *webrtc.TrackLocalStaticSample) {
	// Fetch the audio file from HTTP API
	resp, err := http.Get(audioURL)
	if err != nil {
		fmt.Println("Failed to fetch audio file.")
		return
	}
	defer resp.Body.Close()

	ogg, _, err := oggreader.NewWith(resp.Body)
	if err != nil {
		panic(err)
	}

	ticker := time.NewTicker(oggPageDuration)
	defer ticker.Stop()

	var lastGranule uint64
	for range ticker.C {
		pageData, pageHeader, err := ogg.ParseNextPage()
		if errors.Is(err, io.EOF) {
			fmt.Println("All audio pages parsed.")
			break
		}
		if err != nil {
			panic(err)
		}

		sampleCount := float64(pageHeader.GranulePosition - lastGranule)
		lastGranule = pageHeader.GranulePosition
		sampleDuration := time.Duration((sampleCount/48000)*1000) * time.Millisecond

		if writeErr := musicTrack.WriteSample(media.Sample{Data: pageData, Duration: sampleDuration}); writeErr != nil {
			panic(writeErr)
		}
	}
}
